baseURL = "https://zLeibston.github.io/"
languageCode = "zh-cn"
title = "zLeibston's World"
theme = "PaperMod"

[params]
  defaultTheme = "auto" # è‡ªåŠ¨è·Ÿéšç³»ç»Ÿï¼ˆç™½å¤©/é»‘å¤œï¼‰

  # --- æ ¸å¿ƒè®¾ç½®ï¼šå¼€å¯ä¸ªäººåç‰‡æ¨¡å¼ ---
  [params.profileMode]
    enabled = true
    title = "zLeibston" # è¿™é‡Œæ”¹ä½ çš„åå­—
    subtitle = "ç»™æ—¶å…‰ä»¥ç”Ÿå‘½" # è¿™é‡Œæ”¹ä½ çš„ç­¾å
    # ä¸‹é¢è¿™ä¸ªé­”æ³•é“¾æ¥ä¼šè‡ªåŠ¨æŠ“å–ä½  GitHub çš„å¤´åƒï¼ä¸ç”¨è‡ªå·±ä¸Šä¼ ï¼
    imageUrl = "https://github.com/zLeibston.png" 
    imageTitle = "Avatar"
    imageWidth = 150
    imageHeight = 150

  # --- ç¤¾äº¤å›¾æ ‡ ---
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/zLeibston"
  [[params.socialIcons]]
    name = "bilibili"
    url = "https://www.bilibili.com/" 

# --- é¡¶éƒ¨å¯¼èˆªæ  ---
[[menu.main]]
  identifier = "posts"
  name = "æ–‡ç« åˆ—è¡¨"
  url = "/posts/"
  weight = 1
[[menu.main]]
  identifier = "search"
  name = "ğŸ”æœç´¢"
  url = "/search/"
  weight = 2